version: '3.8'

services:
  db:
    image: postgres:16
    container_name: sentinel_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sentinel_password
      POSTGRES_DB: sentinel_cloud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: